/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbjadPanel.java
 *
 * Created on Aug 7, 2012, 7:58:01 PM
 */

package lcs.ui.panels;

import java.awt.Font;

/**
 *
 * @author Timothy
 */
public class AbjadPanel extends javax.swing.JPanel {

    /** Creates new form AbjadPanel */
    public AbjadPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abjadButtonGroup = new javax.swing.ButtonGroup();
        abjadFontLabel = new javax.swing.JLabel();
        abjadBorrowedRadio = new javax.swing.JRadioButton();
        abjadCustomRadio = new javax.swing.JRadioButton();
        abjadFontField = new javax.swing.JTextField();
        abjadChooseFontButton = new javax.swing.JButton();
        abjadNumberGlyphslabel = new javax.swing.JLabel();
        abjadNumberGlyphsSpinner = new javax.swing.JSpinner();
        abjadGlyphNumberDropDown = new javax.swing.JComboBox();
        abjadUsedInLabel = new javax.swing.JLabel();
        abjadUsedInDropDown = new javax.swing.JComboBox();
        abjadShowVowelsCheck = new javax.swing.JCheckBox();
        abjadTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        abjadFontLabel.setText("Font");

        abjadButtonGroup.add(abjadBorrowedRadio);
        abjadBorrowedRadio.setSelected(true);
        abjadBorrowedRadio.setText("Borrowed");

        abjadButtonGroup.add(abjadCustomRadio);
        abjadCustomRadio.setText("Custom");

        abjadFontField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjadFontFieldActionPerformed(evt);
            }
        });

        abjadChooseFontButton.setText("Choose");
        abjadChooseFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjadChooseFontButtonActionPerformed(evt);
            }
        });

        abjadNumberGlyphslabel.setText("Glyphs/Letter");

        abjadNumberGlyphsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        abjadGlyphNumberDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Glyph_1", "Glyph_2", "Glyph_3", "Glyph_4" }));
        abjadGlyphNumberDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjadGlyphNumberDropDownActionPerformed(evt);
            }
        });

        abjadUsedInLabel.setText("Used in");

        abjadUsedInDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Initial", "Init/Med", "Med", "Med/Final", "Final", "Upper", "Lower" }));
        abjadUsedInDropDown.setPreferredSize(new java.awt.Dimension(61, 20));
        abjadUsedInDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjadUsedInDropDownActionPerformed(evt);
            }
        });

        abjadShowVowelsCheck.setText("Show Vowels");
        abjadShowVowelsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjadShowVowelsCheckActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pronunciation", "Glyph 1"
            }
        ));
        abjadTable.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abjadFontLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadBorrowedRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadCustomRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadFontField, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadChooseFontButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abjadNumberGlyphslabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadNumberGlyphsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadGlyphNumberDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(abjadUsedInLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abjadUsedInDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(abjadShowVowelsCheck)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(abjadTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abjadFontField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abjadFontLabel)
                    .addComponent(abjadBorrowedRadio)
                    .addComponent(abjadCustomRadio)
                    .addComponent(abjadChooseFontButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abjadNumberGlyphslabel)
                    .addComponent(abjadShowVowelsCheck)
                    .addComponent(abjadNumberGlyphsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abjadGlyphNumberDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abjadUsedInLabel)
                    .addComponent(abjadUsedInDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abjadTable, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abjadChooseFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjadChooseFontButtonActionPerformed
        lcs.ui.dialogs.lcsFontChooser lfc= new lcs.ui.dialogs.lcsFontChooser(new javax.swing.JFrame());
        lfc.setVisible(true);
        Font daFont = lfc.getSelectedFont();
        abjadFontField.setText(daFont.getFontName());
        //tcr2.setFontName(daFont.getFontName());
        //for(int a=0;a<alphaTable.getRowCount();a++){
        //    alphaTable.setValueAt(alphaTable.getValueAt(a, 0), a, 1);
        //}
        //characterLabel.setFont(daFont);
    }//GEN-LAST:event_abjadChooseFontButtonActionPerformed

    private void abjadGlyphNumberDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjadGlyphNumberDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abjadGlyphNumberDropDownActionPerformed

    private void abjadUsedInDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjadUsedInDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abjadUsedInDropDownActionPerformed

    private void abjadShowVowelsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjadShowVowelsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abjadShowVowelsCheckActionPerformed

    private void abjadFontFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjadFontFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abjadFontFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abjadBorrowedRadio;
    private javax.swing.ButtonGroup abjadButtonGroup;
    private javax.swing.JButton abjadChooseFontButton;
    private javax.swing.JRadioButton abjadCustomRadio;
    private javax.swing.JTextField abjadFontField;
    private javax.swing.JLabel abjadFontLabel;
    private javax.swing.JComboBox abjadGlyphNumberDropDown;
    private javax.swing.JSpinner abjadNumberGlyphsSpinner;
    private javax.swing.JLabel abjadNumberGlyphslabel;
    private javax.swing.JCheckBox abjadShowVowelsCheck;
    private javax.swing.JScrollPane abjadTable;
    private javax.swing.JComboBox abjadUsedInDropDown;
    private javax.swing.JLabel abjadUsedInLabel;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
