/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlphabetPanel.java
 *
 * Created on Aug 7, 2012, 7:57:42 PM
 */

package lcs.ui.panels;

import java.awt.Font;
/**
 *
 * @author Timothy
 */
public class AlphabetPanel extends javax.swing.JPanel {

    /** Creates new form AlphabetPanel */
    public AlphabetPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alphaButtonGroup = new javax.swing.ButtonGroup();
        alphabetBorrowedRadio = new javax.swing.JRadioButton();
        alphabetCustomRadio = new javax.swing.JRadioButton();
        alphabetFontField = new javax.swing.JTextField();
        alphaChooseFontButton = new javax.swing.JButton();
        numberGlyphsLabel = new javax.swing.JLabel();
        alphaGlyphNumSpinner = new javax.swing.JSpinner();
        alphaGlyphNumberCombo = new javax.swing.JComboBox();
        alphabetUsedInLabel = new javax.swing.JLabel();
        alphaUsedInCombo = new javax.swing.JComboBox();
        alphabetCapsRuleLabel = new javax.swing.JLabel();
        alphaCapRuleCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        alphabetTable = new javax.swing.JTable();
        alphabetFontLabel = new javax.swing.JLabel();

        alphaButtonGroup.add(alphabetBorrowedRadio);
        alphabetBorrowedRadio.setSelected(true);
        alphabetBorrowedRadio.setText("Borrowed");

        alphaButtonGroup.add(alphabetCustomRadio);
        alphabetCustomRadio.setText("Custom");

        alphabetFontField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphabetFontFieldActionPerformed(evt);
            }
        });

        alphaChooseFontButton.setText("Choose");
        alphaChooseFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaChooseFontButtonActionPerformed(evt);
            }
        });

        numberGlyphsLabel.setText("Glyphs/Letter");

        alphaGlyphNumSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        alphaGlyphNumberCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Glyph_1", "Glyph_2", "Glyph_3", "Glyph_4" }));
        alphaGlyphNumberCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaGlyphNumberComboActionPerformed(evt);
            }
        });

        alphabetUsedInLabel.setText("Used in");

        alphaUsedInCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Upper", "Lower", "Initial", "Init/Med", "Medial", "Med/Fin", "Final" }));
        alphaUsedInCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaUsedInComboActionPerformed(evt);
            }
        });

        alphabetCapsRuleLabel.setText("Capitalization Rule");
        alphabetCapsRuleLabel.setEnabled(false);

        alphaCapRuleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sentence", "Nouns", "Words", "None" }));
        alphaCapRuleCombo.setEnabled(false);

        alphabetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pronunciation", "Glyph 1"
            }
        ));
        jScrollPane1.setViewportView(alphabetTable);

        alphabetFontLabel.setText("Font");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberGlyphsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaGlyphNumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaGlyphNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(alphabetUsedInLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaUsedInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alphabetCapsRuleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaCapRuleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alphabetFontLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphabetBorrowedRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphabetCustomRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphabetFontField, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaChooseFontButton)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alphabetFontLabel)
                    .addComponent(alphabetBorrowedRadio)
                    .addComponent(alphabetFontField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphaChooseFontButton)
                    .addComponent(alphabetCustomRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberGlyphsLabel)
                    .addComponent(alphabetCapsRuleLabel)
                    .addComponent(alphaCapRuleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphaUsedInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphabetUsedInLabel)
                    .addComponent(alphaGlyphNumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphaGlyphNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alphabetFontFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphabetFontFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphabetFontFieldActionPerformed

    private void alphaChooseFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaChooseFontButtonActionPerformed
        lcs.ui.dialogs.lcsFontChooser lfc= new lcs.ui.dialogs.lcsFontChooser(new javax.swing.JFrame());
        lfc.setVisible(true);
        Font daFont = lfc.getSelectedFont();
        alphabetFontField.setText(daFont.getFontName());
    }//GEN-LAST:event_alphaChooseFontButtonActionPerformed

    private void alphaGlyphNumberComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaGlyphNumberComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphaGlyphNumberComboActionPerformed

    private void alphaUsedInComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaUsedInComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphaUsedInComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup alphaButtonGroup;
    private javax.swing.JComboBox alphaCapRuleCombo;
    private javax.swing.JButton alphaChooseFontButton;
    private javax.swing.JSpinner alphaGlyphNumSpinner;
    private javax.swing.JComboBox alphaGlyphNumberCombo;
    private javax.swing.JComboBox alphaUsedInCombo;
    private javax.swing.JRadioButton alphabetBorrowedRadio;
    private javax.swing.JLabel alphabetCapsRuleLabel;
    private javax.swing.JRadioButton alphabetCustomRadio;
    private javax.swing.JTextField alphabetFontField;
    private javax.swing.JLabel alphabetFontLabel;
    private javax.swing.JTable alphabetTable;
    private javax.swing.JLabel alphabetUsedInLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberGlyphsLabel;
    // End of variables declaration//GEN-END:variables

}
