/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RulesPanel.java
 *
 * Created on Aug 7, 2012, 7:26:57 PM
 */

package lcs.ui.panels;

/**
 *
 * @author Timothy
 */
public class RulesPanel extends javax.swing.JPanel {

    /** Creates new form RulesPanel */
    public RulesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcsMain1 = new lcs.lcsMain();
        jScrollPane1 = new javax.swing.JScrollPane();
        posRulesTable = new javax.swing.JTable();
        syllablePatternLabel = new javax.swing.JLabel();
        partOfSpeechLabel = new javax.swing.JLabel();
        syllablePatternField = new javax.swing.JTextField();
        maxSyllablesLabel = new javax.swing.JLabel();
        maxSyllablesSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        declensionTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        conugationTable = new javax.swing.JTable();
        declensionLabel = new javax.swing.JLabel();
        conjugationLabel = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        posRulesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Adjective", null, null, new Integer(-1), null, null},
                {"Adverb", null, null, new Integer(-1), null, null},
                {"Article", null, null, new Integer(-1), null, null},
                {"Conjunction", null, null, new Integer(-1), null, null},
                {"Interjection", null, null, new Integer(-1), null, null},
                {"Noun", null, null, new Integer(-1), null, null},
                {"Preposition", null, null, new Integer(-1), null, null},
                {"Verb", null, null, new Integer(-1), null, null}
            },
            new String [] {
                "PoS", "Enabled", "Rule", "Excep %", "Prefix/Suffix", "Add/Replace"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(posRulesTable);
        posRulesTable.getColumnModel().getColumn(0).setResizable(false);

        syllablePatternLabel.setText("Syllable Pattern");

        partOfSpeechLabel.setText("Part of Speech Rules");

        syllablePatternField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syllablePatternFieldActionPerformed(evt);
            }
        });

        maxSyllablesLabel.setText("Maximum # Syllables");

        maxSyllablesSpinner.setModel(new javax.swing.SpinnerNumberModel(3, 2, 5, 1));
        maxSyllablesSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxSyllablesSpinnerStateChanged(evt);
            }
        });

        declensionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Person", "Singular", "Plural"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        declensionTable.setEnabled(false);
        jScrollPane2.setViewportView(declensionTable);

        conugationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Case", "Singular", "Plural"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        conugationTable.setEnabled(false);
        jScrollPane3.setViewportView(conugationTable);

        declensionLabel.setText("Noun Declension");
        declensionLabel.setEnabled(false);

        conjugationLabel.setText("Verb Conjugation");
        conjugationLabel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addComponent(partOfSpeechLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(declensionLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conjugationLabel)
                                .addGap(177, 177, 177))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(syllablePatternLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(syllablePatternField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(maxSyllablesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxSyllablesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(partOfSpeechLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(syllablePatternLabel)
                    .addComponent(syllablePatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxSyllablesLabel)
                    .addComponent(maxSyllablesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(declensionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conjugationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maxSyllablesSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxSyllablesSpinnerStateChanged
        Integer i=(Integer)maxSyllablesSpinner.getValue();
        lcsMain1.setMaximumSyllables(i.intValue());
    }//GEN-LAST:event_maxSyllablesSpinnerStateChanged

    private void syllablePatternFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syllablePatternFieldActionPerformed
        lcs.model.lcsSyllableStructure syl = new lcs.model.lcsSyllableStructure(
                syllablePatternField.getText());
        lcsMain1.setSyllable(syl);
    }//GEN-LAST:event_syllablePatternFieldActionPerformed

    public void setMain(lcs.lcsMain lcsm){
        lcsMain1=lcsm;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conjugationLabel;
    private javax.swing.JTable conugationTable;
    private javax.swing.JLabel declensionLabel;
    private javax.swing.JTable declensionTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private lcs.lcsMain lcsMain1;
    private javax.swing.JLabel maxSyllablesLabel;
    private javax.swing.JSpinner maxSyllablesSpinner;
    private javax.swing.JLabel partOfSpeechLabel;
    private javax.swing.JTable posRulesTable;
    private javax.swing.JTextField syllablePatternField;
    private javax.swing.JLabel syllablePatternLabel;
    // End of variables declaration//GEN-END:variables

}
