/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RulesPanel.java
 *
 * Created on Aug 7, 2012, 5:31:38 PM
 */

package lcs.ui.panels;

/**
 *
 * @author Timothy
 */
public class SoundsPanel extends javax.swing.JPanel {

    /** Creates new form RulesPanel */
    public SoundsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcsMain1 = new lcs.lcsMain();
        consonantsScroller = new javax.swing.JScrollPane();
        consonantsTable = new javax.swing.JTable();
        vowelsScroller = new javax.swing.JScrollPane();
        vowelsTable = new javax.swing.JTable();
        consonantsLabel = new javax.swing.JLabel();
        vowelsLabel = new javax.swing.JLabel();
        consonantsSpinner = new javax.swing.JSpinner();
        vowelsSpinner = new javax.swing.JSpinner();
        consonantNumLabel = new javax.swing.JLabel();
        vowelsNumLabel = new javax.swing.JLabel();
        updateVowelsButton = new javax.swing.JButton();
        updateConsonantsButton = new javax.swing.JButton();

        consonantsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"u0062", "b	"},
                {"u0063", "c	"},
                {"u0064", "d"},
                {"u0066", "f"},
                {"u0067", "g"},
                {"u0068", "h"},
                {"u006a", "j"},
                {"u006b", "k"},
                {"u006c", "l"},
                {"u006d", "m"},
                {"u006e", "n"},
                {"u0070", "p"},
                {"u0071", "q"},
                {"u0072", "r"},
                {"u0073", "s"},
                {"u0074", "t"},
                {"u0076", "v"},
                {"u0077", "w"},
                {"u0078", "x"},
                {"u0079", "y"},
                {"u007a", "z"}
            },
            new String [] {
                "Code Point", "Display"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        consonantsScroller.setViewportView(consonantsTable);

        vowelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"u0061", "a"},
                {"u0065", "e"},
                {"u0069", "i"},
                {"u006f", "o"},
                {"u0075", "u"}
            },
            new String [] {
                "Code Point", "Display"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vowelsScroller.setViewportView(vowelsTable);

        consonantsLabel.setText("Consonants");

        vowelsLabel.setText("Vowels");

        consonantsSpinner.setValue(21);

        vowelsSpinner.setValue(5);

        consonantNumLabel.setText("Number");

        vowelsNumLabel.setText("Number");

        updateVowelsButton.setText("Update");

        updateConsonantsButton.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consonantsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addComponent(consonantNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(consonantsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(consonantsScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateConsonantsButton)
                        .addGap(255, 255, 255)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateVowelsButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vowelsScroller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(vowelsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vowelsNumLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(vowelsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vowelsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consonantsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vowelsLabel)
                    .addComponent(consonantsLabel)
                    .addComponent(vowelsNumLabel)
                    .addComponent(consonantNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vowelsScroller, 0, 0, Short.MAX_VALUE)
                    .addComponent(consonantsScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateConsonantsButton)
                    .addComponent(updateVowelsButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        public void setMain(lcs.lcsMain lcsm){
        lcsMain1 = lcsm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consonantNumLabel;
    private javax.swing.JLabel consonantsLabel;
    private javax.swing.JScrollPane consonantsScroller;
    private javax.swing.JSpinner consonantsSpinner;
    private javax.swing.JTable consonantsTable;
    private lcs.lcsMain lcsMain1;
    private javax.swing.JButton updateConsonantsButton;
    private javax.swing.JButton updateVowelsButton;
    private javax.swing.JLabel vowelsLabel;
    private javax.swing.JLabel vowelsNumLabel;
    private javax.swing.JScrollPane vowelsScroller;
    private javax.swing.JSpinner vowelsSpinner;
    private javax.swing.JTable vowelsTable;
    // End of variables declaration//GEN-END:variables

}
