/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WritingSystemPanel.java
 *
 * Created on Aug 7, 2012, 5:44:47 PM
 */

package lcs.ui.panels;

/**
 *
 * @author Timothy
 */
public class WritingSystemPanel extends javax.swing.JPanel {

    /** Creates new form WritingSystemPanel */
    public WritingSystemPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        writingSystemPane = new javax.swing.JTabbedPane();
        alphabetPanel1 = new lcs.ui.panels.AlphabetPanel();
        abjadPanel1 = new lcs.ui.panels.AbjadPanel();
        abugidaPanel1 = new lcs.ui.panels.AbugidaPanel();
        syllabaryPanel1 = new lcs.ui.panels.SyllabaryPanel();
        upButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        previewLabel = new javax.swing.JLabel();
        backPageButton = new javax.swing.JButton();
        backCharButton = new javax.swing.JButton();
        forwardCharButton = new javax.swing.JButton();
        forwardPageButton = new javax.swing.JButton();
        jumpToLabel = new javax.swing.JLabel();
        jumpToField = new javax.swing.JTextField();
        jumpToValueLabel = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        writingSystemPane.addTab("Alphabet", alphabetPanel1);
        writingSystemPane.addTab("Abjad", abjadPanel1);
        writingSystemPane.addTab("Abugida", abugidaPanel1);
        writingSystemPane.addTab("Syllabary", syllabaryPanel1);

        upButton.setText("^");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        downButton.setText("V");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        leftButton.setText("<");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setText(">");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        previewLabel.setFont(new java.awt.Font("Tahoma", 0, 36));
        previewLabel.setText("XXAXX");

        backPageButton.setText("<<");
        backPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPageButtonActionPerformed(evt);
            }
        });

        backCharButton.setText("<");
        backCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCharButtonActionPerformed(evt);
            }
        });

        forwardCharButton.setText(">");
        forwardCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardCharButtonActionPerformed(evt);
            }
        });

        forwardPageButton.setText(">>");
        forwardPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardPageButtonActionPerformed(evt);
            }
        });

        jumpToLabel.setText("Jump To");

        jumpToValueLabel.setText("41");

        jButton10.setText("Auto Fill");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(writingSystemPane, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(downButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jumpToLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jumpToField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backPageButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(backCharButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(forwardCharButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(forwardPageButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jumpToValueLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(previewLabel)))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(writingSystemPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setButton)
                            .addComponent(leftButton)
                            .addComponent(rightButton)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backCharButton)
                            .addComponent(forwardCharButton)
                            .addComponent(forwardPageButton)
                            .addComponent(backPageButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumpToLabel)
                            .addComponent(jumpToField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumpToValueLabel))))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upButtonActionPerformed

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftButtonActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downButtonActionPerformed

    private void backPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backPageButtonActionPerformed

    private void backCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCharButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backCharButtonActionPerformed

    private void forwardCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardCharButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwardCharButtonActionPerformed

    private void forwardPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardPageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwardPageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lcs.ui.panels.AbjadPanel abjadPanel1;
    private lcs.ui.panels.AbugidaPanel abugidaPanel1;
    private lcs.ui.panels.AlphabetPanel alphabetPanel1;
    private javax.swing.JButton backCharButton;
    private javax.swing.JButton backPageButton;
    private javax.swing.JButton downButton;
    private javax.swing.JButton forwardCharButton;
    private javax.swing.JButton forwardPageButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JTextField jumpToField;
    private javax.swing.JLabel jumpToLabel;
    private javax.swing.JLabel jumpToValueLabel;
    private javax.swing.JButton leftButton;
    private javax.swing.JLabel previewLabel;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton setButton;
    private lcs.ui.panels.SyllabaryPanel syllabaryPanel1;
    private javax.swing.JButton upButton;
    private javax.swing.JTabbedPane writingSystemPane;
    // End of variables declaration//GEN-END:variables

}
