/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseFontWiz.java
 *
 * Created on Sep 15, 2012, 2:07:26 PM
 */

package lcs.ui.panels.wizard;

/**
 *
 * @author Timothy
 */
public class ChooseFontWiz extends javax.swing.JPanel {

    /** Creates new form ChooseFontWiz */
    public ChooseFontWiz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        ChooseWSFontLabel = new javax.swing.JLabel();
        borrowedFontButton = new javax.swing.JRadioButton();
        customFontButton = new javax.swing.JRadioButton();
        fontField = new javax.swing.JTextField();
        chooseFontButton = new javax.swing.JButton();
        instructionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        ChooseWSFontLabel.setText("Choose Writing System Font");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        add(ChooseWSFontLabel, gridBagConstraints);

        buttonGroup1.add(borrowedFontButton);
        borrowedFontButton.setSelected(true);
        borrowedFontButton.setText("Borrowed");
        borrowedFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedFontButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        add(borrowedFontButton, gridBagConstraints);

        buttonGroup1.add(customFontButton);
        customFontButton.setText("Custom");
        customFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customFontButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(customFontButton, gridBagConstraints);

        fontField.setText("Code2000");
        fontField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(fontField, gridBagConstraints);

        chooseFontButton.setText("Choose...");
        chooseFontButton.setEnabled(false);
        chooseFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFontButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 10);
        add(chooseFontButton, gridBagConstraints);

        instructionsLabel.setText("<html> Choose the font that your new language will be displayed with:<br><br>\n<b>Borrowed</b> = You will choose the display characters from those<br>\navailable in the \\\"Code 2000\\\" font.<br><br>\n<b>Custom</b> = You wil choose them from a font of your choosing. </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.85;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(instructionsLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void customFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customFontButtonActionPerformed
        chooseFontButton.setEnabled(true);
        fontField.setEnabled(true);
    }//GEN-LAST:event_customFontButtonActionPerformed

    private void borrowedFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedFontButtonActionPerformed
        chooseFontButton.setEnabled(false);
        fontField.setEnabled(false);
    }//GEN-LAST:event_borrowedFontButtonActionPerformed

    private void chooseFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFontButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseFontButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChooseWSFontLabel;
    private javax.swing.JRadioButton borrowedFontButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseFontButton;
    private javax.swing.JRadioButton customFontButton;
    private javax.swing.JTextField fontField;
    private javax.swing.JLabel instructionsLabel;
    // End of variables declaration//GEN-END:variables

}
