/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseWritingSystemWiz.java
 *
 * Created on Sep 15, 2012, 12:27:09 PM
 */

package lcs.ui.panels.wizard;

/**
 *
 * @author Timothy
 */
public class ChooseWritingSystemWiz extends javax.swing.JPanel {

    /** Creates new form ChooseWritingSystemWiz */
    public ChooseWritingSystemWiz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectWritingSystemTypeLable = new javax.swing.JLabel();
        alphabetSystemRadio = new javax.swing.JRadioButton();
        abjadSystemRadio = new javax.swing.JRadioButton();
        abugidaSystemRadio = new javax.swing.JRadioButton();
        syllabarySystemRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        selectWritingSystemTypeLable.setText("Select Type of Writing System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        add(selectWritingSystemTypeLable, gridBagConstraints);

        buttonGroup1.add(alphabetSystemRadio);
        alphabetSystemRadio.setSelected(true);
        alphabetSystemRadio.setText("Alphabet");
        alphabetSystemRadio.setToolTipText("Both vowels and consonants written on the line.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(alphabetSystemRadio, gridBagConstraints);

        buttonGroup1.add(abjadSystemRadio);
        abjadSystemRadio.setText("Abjad");
        abjadSystemRadio.setToolTipText("<html>Consonants written on the line, vowels are optionally<br>wriiten as diacritical marks either above or below the line.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 17);
        add(abjadSystemRadio, gridBagConstraints);

        buttonGroup1.add(abugidaSystemRadio);
        abugidaSystemRadio.setText("Abugida");
        abugidaSystemRadio.setToolTipText("<html>Vowels are merged with the neighboring consonant with dicritcal marks,<br>one of the vowels is usually understood if there are no other vowel marks.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(abugidaSystemRadio, gridBagConstraints);

        buttonGroup1.add(syllabarySystemRadio);
        syllabarySystemRadio.setText("Syllabary");
        syllabarySystemRadio.setToolTipText("<html>There is a symbol for each syllable that can be formed,<br>these symbols are written on the line.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(syllabarySystemRadio, gridBagConstraints);

        jLabel1.setText("<html>Hover the mouse over the writing system type to see a description<br>of that system.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abjadSystemRadio;
    private javax.swing.JRadioButton abugidaSystemRadio;
    private javax.swing.JRadioButton alphabetSystemRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel selectWritingSystemTypeLable;
    private javax.swing.JRadioButton syllabarySystemRadio;
    // End of variables declaration//GEN-END:variables

}
