/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PosRulesWiz.java
 *
 * Created on Sep 15, 2012, 10:54:00 AM
 */

package lcs.ui.panels.wizard;

/**
 *
 * @author Timothy
 */
public class PosRulesWiz extends javax.swing.JPanel {

    /** Creates new form PosRulesWiz */
    public PosRulesWiz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        posRulesLabel = new javax.swing.JLabel();
        PosRulesScroller = new javax.swing.JScrollPane();
        posRulesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        posRulesLabel.setText("Set the Part of Speech Rules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        add(posRulesLabel, gridBagConstraints);

        PosRulesScroller.setPreferredSize(new java.awt.Dimension(380, 112));

        posRulesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Adjective", null, null, new Integer(-1), null, null},
                {"Adverb", null, null, new Integer(-1), null, null},
                {"Article", null, null, new Integer(-1), null, null},
                {"Noun", null, null, new Integer(-1), null, null},
                {"Preposition", null, null, new Integer(-1), null, null},
                {"Pronoun", null, null, new Integer(-1), null, null},
                {"Verb", null, null, new Integer(-1), null, null}
            },
            new String [] {
                "PoS", "Enabled", "Rule", "Exception %", "Prefix/Suffix", "Add/Replace"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        posRulesTable.setPreferredSize(new java.awt.Dimension(380, 112));
        PosRulesScroller.setViewportView(posRulesTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.65;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        add(PosRulesScroller, gridBagConstraints);

        jLabel1.setText("<html>Choose how you want the words to vary depending on the part of speech.  In the \"prefix/suffix\" and \"add/replace\" columns, if checked the latter is chosen.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(67, 28));
        jLabel1.setPreferredSize(new java.awt.Dimension(380, 85));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PosRulesScroller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel posRulesLabel;
    private javax.swing.JTable posRulesTable;
    // End of variables declaration//GEN-END:variables

}
