/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SoundsWiz.java
 *
 * Created on Sep 15, 2012, 11:14:08 AM
 */

package lcs.ui.panels.wizard;

/**
 *
 * @author Timothy
 */
public class SoundsWiz extends javax.swing.JPanel {

    /** Creates new form SoundsWiz */
    public SoundsWiz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selectSoundsLabel = new javax.swing.JLabel();
        consonantsTableLabel = new javax.swing.JLabel();
        numberConsonantsLabel = new javax.swing.JLabel();
        vowelsTableLabel = new javax.swing.JLabel();
        numberConsonantsSpinner = new javax.swing.JSpinner();
        numberVowelsLabel = new javax.swing.JLabel();
        numberVowelsSpinner = new javax.swing.JSpinner();
        consonantsScroller = new javax.swing.JScrollPane();
        consonantsTable = new javax.swing.JTable();
        vowelsScroller = new javax.swing.JScrollPane();
        vowelsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        selectSoundsLabel.setText("Select The Sounds");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        add(selectSoundsLabel, gridBagConstraints);

        consonantsTableLabel.setText("Consonants");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.16;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        add(consonantsTableLabel, gridBagConstraints);

        numberConsonantsLabel.setText("Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.16;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(numberConsonantsLabel, gridBagConstraints);

        vowelsTableLabel.setText("Vowels");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.16;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(vowelsTableLabel, gridBagConstraints);

        numberConsonantsSpinner.setModel(new javax.swing.SpinnerNumberModel(21, 5, 40, 1));
        numberConsonantsSpinner.setValue(21);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.16;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        add(numberConsonantsSpinner, gridBagConstraints);

        numberVowelsLabel.setText("Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.16;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(numberVowelsLabel, gridBagConstraints);

        numberVowelsSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 40, 1));
        numberVowelsSpinner.setValue(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 0.17;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        add(numberVowelsSpinner, gridBagConstraints);

        consonantsScroller.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        consonantsScroller.setPreferredSize(new java.awt.Dimension(180, 200));

        consonantsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code Point", "Pronunciation"
            }
        ));
        consonantsScroller.setViewportView(consonantsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(consonantsScroller, gridBagConstraints);

        vowelsScroller.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vowelsScroller.setPreferredSize(new java.awt.Dimension(180, 200));

        vowelsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code Point", "Pronunciation"
            }
        ));
        vowelsScroller.setViewportView(vowelsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(vowelsScroller, gridBagConstraints);

        jButton1.setText("Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        add(jButton1, gridBagConstraints);

        jButton2.setText("Update");
        jButton2.setActionCommand("Update2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        add(jButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consonantsScroller;
    private javax.swing.JTable consonantsTable;
    private javax.swing.JLabel consonantsTableLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel numberConsonantsLabel;
    private javax.swing.JSpinner numberConsonantsSpinner;
    private javax.swing.JLabel numberVowelsLabel;
    private javax.swing.JSpinner numberVowelsSpinner;
    private javax.swing.JLabel selectSoundsLabel;
    private javax.swing.JScrollPane vowelsScroller;
    private javax.swing.JTable vowelsTable;
    private javax.swing.JLabel vowelsTableLabel;
    // End of variables declaration//GEN-END:variables

}
