/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SyllablePatternWiz.java
 *
 * Created on Sep 15, 2012, 10:37:25 AM
 */

package lcs.ui.panels.wizard;

import javax.swing.*;

/**
 *
 * @author Timothy
 */
public class SyllablePatternWiz extends JPanel {

    /** Creates new form SyllablePatternWiz */
    public SyllablePatternWiz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        syllablePatternLabel = new javax.swing.JLabel();
        syllablePatternField = new javax.swing.JTextField();
        maxSyllablesLabel = new javax.swing.JLabel();
        maxSyllablesCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.GridBagLayout());

        syllablePatternLabel.setText("Syllable Pattern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(syllablePatternLabel, gridBagConstraints);

        syllablePatternField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syllablePatternFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(syllablePatternField, gridBagConstraints);

        maxSyllablesLabel.setText("Maximum # Syllables");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 10);
        add(maxSyllablesLabel, gridBagConstraints);

        maxSyllablesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        add(maxSyllablesCombo, gridBagConstraints);

        jLabel1.setText("Select Syllable Pattern and Maximum Syllable Count per Word.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("<html>\nSet the syllable pattern (see manual for full description).<br><br>\nSet the maximum nuber of syllables allowed in a word.\n<html>\n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void syllablePatternFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syllablePatternFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syllablePatternFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox maxSyllablesCombo;
    private javax.swing.JLabel maxSyllablesLabel;
    private javax.swing.JTextField syllablePatternField;
    private javax.swing.JLabel syllablePatternLabel;
    // End of variables declaration//GEN-END:variables

}
